"""seconds positive

Revision ID: 3ce0d580d2bd
Revises: d301f96aeda5
Create Date: 2026-09-25 17:29:13.649755

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ce0d580d2bd"
down_revision: str | Sequence[str] | None = "d301f96aeda5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("seconds_positivos", "track", "seconds > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("seconds_positivos", "track", type_="check")
    # ### end Alembic commands ###
