"""cascade on foreign keys

Revision ID: f35cabe5acd6
Revises: 3ce0d580d2bd
Create Date: 2026-09-25 19:22:16.486256

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f35cabe5acd6"
down_revision: str | Sequence[str] | None = "3ce0d580d2bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("playlist_track_playlist_id_fkey"), "playlist_track", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("playlist_track_track_id_fkey"), "playlist_track", type_="foreignkey"
    )
    op.create_foreign_key(
        "playlist_track_track_id_fkey",
        "playlist_track",
        "track",
        ["track_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "playlist_track_playlist_id_fkey",
        "playlist_track",
        "playlist",
        ["playlist_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("track_artist_id_fkey"), "track", type_="foreignkey")
    op.create_foreign_key(
        "track_artist_id_fkey",
        "track",
        "artist",
        ["artist_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("track_artist_id_fkey", "track", type_="foreignkey")
    op.create_foreign_key(
        op.f("track_artist_id_fkey"), "track", "artist", ["artist_id"], ["id"]
    )
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "playlist_track_playlist_id_fkey", "playlist_track", type_="foreignkey"
    )
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "playlist_track_track_id_fkey", "playlist_track", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("playlist_track_track_id_fkey"),
        "playlist_track",
        "track",
        ["track_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("playlist_track_playlist_id_fkey"),
        "playlist_track",
        "playlist",
        ["playlist_id"],
        ["id"],
    )
    # ### end Alembic commands ###
